# Generated by Django 5.2.3 on 2025-07-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking2_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='class_date',
            field=models.DateTimeField(),
        ),
    ]
