# Generated by Django 5.2.3 on 2025-07-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booking_class_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking2',
            name='class_date',
            field=models.DateTimeField(default='2025-07-13T14:30:00'),
            preserve_default=False,
        ),
    ]
